# Generated by Django 4.2.30 on 2026-06-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
    ]
